# This is a sample Python script.

# Press Shift+F10 to execute it or replace it with your code.
# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

if __name__ != '__main__':
    pass

#
# def print_hi(name):
#     # Use a breakpoint in the code line below to debug your script.
#     print(f'Hi, {name}')  # Press Ctrl+F8 to toggle the breakpoint.
#
#
# Press the green button in the gutter to run the script.
else:
    # ex 3
    f = input("ввидите слово: ")
    print("в слове синвалов: " + str(len(f)))
    # ex 1
#     a = 5
#     # d = input("ввидите число 1")
#     # a = input("ввидите число 2")
#     # res = d == a
#     # print("результат сравнения "+str(res ))
      # ex 2
#     g = input("ввидете сторону квадрата 1")
#     e = input("ввидете сторону квадрата 2")
#     p1 = 4* int(g)
#     p2 = 4* int(e)
#     print("peremeters of squares 1 and 2 : "+str(p1 )+" "+str(p2))

#     b = 5
#     print(a + b)
#     c=78
#     d=99
#     t=c
#     c=d
#     d =t
#     print(c)
#     print(d)
#     dollors = 1
#     rate = 97
#     rubls= rate*dollors
#     print(rubls)
#     maths = 5
#     music = 4
#     rus = 3
#     avg = (maths+music+rus)/3
#     print(avg)
#     x = 10
#     y =3
#     dif =x%y
#     print(dif)
#
# # See PyCharm help at https://www.jetbrains.com/help/pycharm/
#
# import turtle
# turtle.color("blue")
# turtle.right(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(60)
#
# turtle.speed(0)
# turtle.color("yellow")
# turtle.right(90)
# turtle.forward(30)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(30)
# turtle.right(90)
# turtle.color("black")
# turtle.forward(30)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(60)
# turtle.left(90)
# turtle.color("green")
# turtle.forward(30)
# turtle.right(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(90)
# turtle.color("red")
# turtle.forward(30)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# import turtle
#
# urtle.forward(240)
# turtle.left(135)
# turtle.forward(180)
# turtle.left(90)
# turtle.forward(180)
# turtle.left(135)
# turtle.forward(240)
# turtle.right(90)
# turtle.forward(240)
# turtle.right(90)
# turtle.forward(230)
# turtle.right(90)
# turtle.forward(240)
# turtle.right(180)
# turtle.forward(240)
# turtle.left(90)
# turtle.forward(100)
# turtle.left(90)
# turtle.forward(180)
# turtle.left(90)
# turtle.forward(100)
# turtle.right(180)
# turtle.forward(230)
# turtle.right(90)
# turtle.forward(80)
# turtle.right(90)
# turtle.forward(80)
# turtle.right(90)
# turtle.forward(80)
# t
# turtle.speed(987654390257565843)
# turtle.mainloop()
# import turtle
#
# turtle.forward(240)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(120)
# turtle.right(180)
# turtle.forward(60)
# turtle.right(90)
# turtle.forward(480)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(120)
# turtle.right(180)
# turtle.forward(60)
# turtle.right(90)
# turtle.forward(240)
# turtle.right(90)
# turtle.forward(240)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(120)
# turtle.right(180)
# turtle.forward(60)
# turtle.right(90)
# turtle.forward(480)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(120)
# turtle.right(180)
# turtle.forward(60)
# turtle.right(90)
# turtle.forward(240)
# turtle.right(45)
# turtle.forward(240)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(120)
# turtle.right(180)
# turtle.forward(60)
# turtle.right(90)
# turtle.forward(480)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(120)
# turtle.right(180)
# turtle.forward(60)
# turtle.right(90)
# turtle.forward(240)
# turtle.left(90)
# turtle.forward(240)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(120)
# turtle.right(180)
# turtle.forward(60)
# turtle.right(90)
# turtle.forward(480)
# turtle.right(90)
# turtle.forward(60)
# turtle.right(180)
# turtle.forward(120)
# turtle.right(180)
# turtle.forward(60)
# turtle.right(90)
# turtle.right(45)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.forward(90)
# turtle.right(90)
# turtle.forward

# turtle.mainloop()
